<a href="https://colab.research.google.com/github/shumetgr22/shumetgr22/blob/main/A1_22203262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [142]:
# importing neccesary libraries
import numpy as np
import pandas as pd
import io
from google.colab import files, drive
drive.mount('/content/drive')



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [143]:
# Exercise 1
# Create row and column vectors using input method
row_vector = np.array(input("Enter space-separated values for row vector: ").split(), dtype=float)
column_vector = np.array(input("Enter space-separated values for column vector: ").split(), dtype=float)

Enter space-separated values for row vector: 4 5 6 8 7
Enter space-separated values for column vector: 8 9 7 4 5


In [144]:

# Manually create row and column vectors
row_vector_manual = np.array([1, 2, 3])
column_vector_manual = np.array([[1], [2], [3]])


In [145]:
row_vector_manual
column_vector_manual

array([[1],
       [2],
       [3]])

In [146]:

# Exercise 2
# Create a 5x5 matrix using input method
matrix_a = np.zeros((5, 5))
for i in range(5):
    matrix_a[i] = np.array(input(f"Enter values for row {i+1}: ").split(), dtype=float)


Enter values for row 1: 4 8 9 5 4
Enter values for row 2: 6 7 8 10 4
Enter values for row 3: 7 9 10 11 7
Enter values for row 4: 6 8 4 11 9
Enter values for row 5: 7 8 5 9 12


In [147]:
matrix_a[0]

array([4., 8., 9., 5., 4.])

In [148]:
# Manually create a 5x5 matrix
matrix_b = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])

In [149]:
matrix_b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
# Exercise 3
third_row = matrix_a[2]
third_row


array([ 7.,  9., 10., 11.,  7.])

In [151]:
# Exercise 4
fourth_column = matrix_a[:, 3]

In [152]:
fourth_column

array([ 5., 10., 11., 11.,  9.])

In [153]:
# Exercise 5
sorted_matrix_row_wise = np.sort(matrix_a, axis=1)
sorted_matrix_column_wise = np.sort(matrix_a, axis=0)

In [154]:
sorted_matrix_row_wise

array([[ 4.,  4.,  5.,  8.,  9.],
       [ 4.,  6.,  7.,  8., 10.],
       [ 7.,  7.,  9., 10., 11.],
       [ 4.,  6.,  8.,  9., 11.],
       [ 5.,  7.,  8.,  9., 12.]])

In [155]:
sorted_matrix_column_wise

array([[ 4.,  7.,  4.,  5.,  4.],
       [ 6.,  8.,  5.,  9.,  4.],
       [ 6.,  8.,  8., 10.,  7.],
       [ 7.,  8.,  9., 11.,  9.],
       [ 7.,  9., 10., 11., 12.]])

In [156]:
a= [2,3,4,5,1]

In [157]:
np.sort(a)

array([1, 2, 3, 4, 5])

In [158]:
# Exercise 6
matrix_b = np.copy(matrix_a)
matrix_b[matrix_b > 2] *= 10

In [159]:
matrix_b

array([[ 40.,  80.,  90.,  50.,  40.],
       [ 60.,  70.,  80., 100.,  40.],
       [ 70.,  90., 100., 110.,  70.],
       [ 60.,  80.,  40., 110.,  90.],
       [ 70.,  80.,  50.,  90., 120.]])

In [160]:
matrix_b

array([[ 40.,  80.,  90.,  50.,  40.],
       [ 60.,  70.,  80., 100.,  40.],
       [ 70.,  90., 100., 110.,  70.],
       [ 60.,  80.,  40., 110.,  90.],
       [ 70.,  80.,  50.,  90., 120.]])

In [161]:
# Exercise 7
matrix_sum = matrix_a + matrix_b
matrix_sum

array([[ 44.,  88.,  99.,  55.,  44.],
       [ 66.,  77.,  88., 110.,  44.],
       [ 77.,  99., 110., 121.,  77.],
       [ 66.,  88.,  44., 121.,  99.],
       [ 77.,  88.,  55.,  99., 132.]])

In [162]:
# Exercise 8
matrix_difference = matrix_a - matrix_b

In [163]:
matrix_difference

array([[ -36.,  -72.,  -81.,  -45.,  -36.],
       [ -54.,  -63.,  -72.,  -90.,  -36.],
       [ -63.,  -81.,  -90.,  -99.,  -63.],
       [ -54.,  -72.,  -36.,  -99.,  -81.],
       [ -63.,  -72.,  -45.,  -81., -108.]])

In [164]:
# Exercise 9
element_wise_product = matrix_a * matrix_b
matrix_multiplication = np.dot(matrix_a, matrix_b)

In [165]:
element_wise_product

array([[ 160.,  640.,  810.,  250.,  160.],
       [ 360.,  490.,  640., 1000.,  160.],
       [ 490.,  810., 1000., 1210.,  490.],
       [ 360.,  640.,  160., 1210.,  810.],
       [ 490.,  640.,  250.,  810., 1440.]])

In [166]:
matrix_multiplication

array([[1850., 2410., 2300., 2900., 2040.],
       [2100., 2810., 2500., 3340., 2460.],
       [2670., 3530., 3140., 4190., 3170.],
       [2290., 3000., 2470., 3560., 2910.],
       [2490., 3250., 2730., 3770., 3200.]])

In [167]:
# Exercise 10
matrix_a /= 18
matrix_b /= 18

In [168]:
matrix_a

array([[0.22222222, 0.44444444, 0.5       , 0.27777778, 0.22222222],
       [0.33333333, 0.38888889, 0.44444444, 0.55555556, 0.22222222],
       [0.38888889, 0.5       , 0.55555556, 0.61111111, 0.38888889],
       [0.33333333, 0.44444444, 0.22222222, 0.61111111, 0.5       ],
       [0.38888889, 0.44444444, 0.27777778, 0.5       , 0.66666667]])

In [169]:
matrix_b

array([[2.22222222, 4.44444444, 5.        , 2.77777778, 2.22222222],
       [3.33333333, 3.88888889, 4.44444444, 5.55555556, 2.22222222],
       [3.88888889, 5.        , 5.55555556, 6.11111111, 3.88888889],
       [3.33333333, 4.44444444, 2.22222222, 6.11111111, 5.        ],
       [3.88888889, 4.44444444, 2.77777778, 5.        , 6.66666667]])

In [170]:

# Exercise 11
inverse_a = np.linalg.inv(matrix_a)
rank_a = np.linalg.matrix_rank(matrix_a)
condition_number_a = np.linalg.cond(matrix_a)
singular_values_a = np.linalg.svd(matrix_a)
norm_a = np.linalg.norm(matrix_a)

inverse_b = np.linalg.inv(matrix_b)
rank_b = np.linalg.matrix_rank(matrix_b)
condition_number_b = np.linalg.cond(matrix_b)
singular_values_b = np.linalg.svd(matrix_b)
norm_b = np.linalg.norm(matrix_b)


In [171]:
inverse_a

array([[  4.03344482,  27.45150502, -28.41471572,  -8.66889632,
         12.5819398 ],
       [  7.88628763,   7.46488294, -14.98996656,   4.27424749,
          0.42140468],
       [ -3.04013378,  -9.54180602,  14.29765886,  -2.19732441,
         -2.49832776],
       [ -4.24414716,  -7.79598662,  11.22742475,   3.88294314,
         -5.44816054],
       [ -3.16053512, -11.16722408,  12.19063545,   0.21070234,
         -0.99331104]])

In [172]:
rank_a

5

In [173]:

condition_number_a

113.38644889838343

In [174]:
singular_values_a

(array([[-0.34828877, -0.52528695,  0.62152351,  0.43510778, -0.16479776],
        [-0.41520834, -0.34438285, -0.53178933, -0.22113896, -0.61424763],
        [-0.51856912, -0.28736679, -0.10765014, -0.33366671,  0.72497198],
        [-0.45477272,  0.43255852, -0.3423785 ,  0.69000463,  0.11289586],
        [-0.48017163,  0.57947177,  0.44955205, -0.41753913, -0.23918967]]),
 array([2.12726423, 0.44270658, 0.2230075 , 0.08031959, 0.01876119]),
 array([[-0.35528749, -0.46589431, -0.41424896, -0.54639381, -0.43193157],
        [ 0.05931206, -0.13842054, -0.71890108,  0.0931256 ,  0.67218352],
        [-0.09107804,  0.283548  ,  0.28428089, -0.77591369,  0.47796197],
        [-0.48750782,  0.7674986 , -0.35793526,  0.0871617 , -0.19382262],
        [-0.79012265, -0.30712972,  0.32038376,  0.2883439 ,  0.30917564]]))

In [175]:
norm_a

2.1858128414340006

In [176]:
inverse_b

array([[ 0.40334448,  2.7451505 , -2.84147157, -0.86688963,  1.25819398],
       [ 0.78862876,  0.74648829, -1.49899666,  0.42742475,  0.04214047],
       [-0.30401338, -0.9541806 ,  1.42976589, -0.21973244, -0.24983278],
       [-0.42441472, -0.77959866,  1.12274247,  0.38829431, -0.54481605],
       [-0.31605351, -1.11672241,  1.21906355,  0.02107023, -0.0993311 ]])

In [177]:
rank_b

5

In [178]:
condition_number_b

113.3864488983834

In [179]:
singular_values_b

(array([[-0.34828877, -0.52528695,  0.62152351,  0.43510778, -0.16479776],
        [-0.41520834, -0.34438285, -0.53178933, -0.22113896, -0.61424763],
        [-0.51856912, -0.28736679, -0.10765014, -0.33366671,  0.72497198],
        [-0.45477272,  0.43255852, -0.3423785 ,  0.69000463,  0.11289586],
        [-0.48017163,  0.57947177,  0.44955205, -0.41753913, -0.23918967]]),
 array([21.27264229,  4.42706578,  2.23007499,  0.80319592,  0.18761186]),
 array([[-0.35528749, -0.46589431, -0.41424896, -0.54639381, -0.43193157],
        [ 0.05931206, -0.13842054, -0.71890108,  0.0931256 ,  0.67218352],
        [-0.09107804,  0.283548  ,  0.28428089, -0.77591369,  0.47796197],
        [-0.48750782,  0.7674986 , -0.35793526,  0.0871617 , -0.19382262],
        [-0.79012265, -0.30712972,  0.32038376,  0.2883439 ,  0.30917564]]))

In [180]:
norm_b

21.858128414340005

In [181]:
# Exercise 12
column_vector_norm = np.linalg.norm(column_vector)
inner_product = np.inner(column_vector, column_vector)
outer_product = np.outer(column_vector, column_vector)

In [182]:
column_vector_norm


15.329709716755891

In [183]:
inner_product

235.0

In [184]:
outer_product

array([[64., 72., 56., 32., 40.],
       [72., 81., 63., 36., 45.],
       [56., 63., 49., 28., 35.],
       [32., 36., 28., 16., 20.],
       [40., 45., 35., 20., 25.]])

In [185]:
# Exercise 13
def derivative(f, a, method='central', h=0.01):
    if method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    elif method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h

def func1(x):
    return np.exp(x)

def func2(x):
    return np.cos(x)

x_value = 0.5
derivative_func1 = derivative(func1, x_value)
derivative_func2 = derivative(func2, x_value)

In [186]:
derivative_func1

1.648748749525375

In [187]:
derivative_func2

-0.4794175482185081

In [188]:
# Exercise 14
# Path to the uploaded file in Google Drive
file_path = '/content/drive/My Drive/AWS.xlsx'

# Load the Excel file into a pandas DataFrame
data = pd.read_excel(file_path)

# Display the first few rows of the DataFrame
data.head()


created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15