<a href="https://colab.research.google.com/github/shumetgr22/shumetgr22/blob/main/A22203262_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing neccesary libraries
import numpy as np                    # importing numpy libary
import pandas as pd                   # importing pandas libary




In [ ]:
# Exercise 1
# Create row and column vectors using input method
row_vector = np.array(input("Enter space-separated values for row vector: ").split(), dtype=float)          # entering row vectors
column_vector = np.array(input("Enter space-separated values for column vector: ").split(), dtype=float)    # entering column vectors

Enter space-separated values for row vector: 2 4 5 6
Enter space-separated values for column vector: 7 8 9 10


In [ ]:
row_vector                   # printing row vector

array([2., 4., 5., 6.])

In [ ]:

column_vector                # printing column vector

array([ 7.,  8.,  9., 10.])

In [ ]:

# Exercise 2
# Create a 5x5 matrix using input method
a = np.zeros((5, 5))
for i in range(5):
    a[i] = np.array(input(f"Enter values for row {i+1}: ").split(), dtype=float)


Enter values for row 1: 8 7 6 5 1
Enter values for row 2: 4 7 8 9 1
Enter values for row 3: 2 4 1 5 7
Enter values for row 4: 4 5 6 8 7
Enter values for row 5: 4 1 7 8 6


In [ ]:
a                           # printing the matrix a

array([[8., 7., 6., 5., 1.],
       [4., 7., 8., 9., 1.],
       [2., 4., 1., 5., 7.],
       [4., 5., 6., 8., 7.],
       [4., 1., 7., 8., 6.]])

In [ ]:
# Manually create a 5x5 matrix
b = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])

In [ ]:
b                       # printing the matrix b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Exercise 3
third_row =a[2]                # printing the third row of matrix a
third_row


array([2., 4., 1., 5., 7.])

In [ ]:
# Exercise 4
fourth_column = a[:, 3]      # printing the fourth column of matrix a

In [ ]:
fourth_column

array([5., 9., 5., 8., 8.])

In [ ]:
# Exercise 5
sorted_matrix_row_wise = np.sort(a, axis=1)      # sorting matrix a row wise
sorted_matrix_column_wise = np.sort(a, axis=0)   # sorting matrix a column wise

In [ ]:
sorted_matrix_row_wise                          # printing sorted matrix a row wise

array([[1., 5., 6., 7., 8.],
       [1., 4., 7., 8., 9.],
       [1., 2., 4., 5., 7.],
       [4., 5., 6., 7., 8.],
       [1., 4., 6., 7., 8.]])

In [ ]:
sorted_matrix_column_wise                       # printing sorted matrix a column wise

array([[2., 1., 1., 5., 1.],
       [4., 4., 6., 5., 1.],
       [4., 5., 6., 8., 6.],
       [4., 7., 7., 8., 7.],
       [8., 7., 8., 9., 7.]])

In [ ]:
# Exercise 6
import numpy as np
copy_a = np.copy(a)                       # creating copy of matrix a
copy_a [copy_a > 2] *= 10                 # multiplying elements of copy_a matrix by 10 which are greater than 2

In [ ]:
copy_a                                   # printing copy_a matrix

array([[80., 70., 60., 50.,  1.],
       [40., 70., 80., 90.,  1.],
       [ 2., 40.,  1., 50., 70.],
       [40., 50., 60., 80., 70.],
       [40.,  1., 70., 80., 60.]])

In [ ]:
# Exercise 7
matrix_sum = a + copy_a                 # summing the matrix a and copy_a
matrix_sum

array([[88., 77., 66., 55.,  2.],
       [44., 77., 88., 99.,  2.],
       [ 4., 44.,  2., 55., 77.],
       [44., 55., 66., 88., 77.],
       [44.,  2., 77., 88., 66.]])

In [ ]:
# Exercise 8
matrix_difference = copy_a-a              # calculating the difference of copy_a and a matrix

In [ ]:
matrix_difference                         # printing the difference of copy_a and a matrix

array([[72., 63., 54., 45.,  0.],
       [36., 63., 72., 81.,  0.],
       [ 0., 36.,  0., 45., 63.],
       [36., 45., 54., 72., 63.],
       [36.,  0., 63., 72., 54.]])

In [ ]:
# Exercise 9
element_wise_product = a * copy_a                # doing element wise multiplication of matrix copy_a and a matrix
matrix_multiplication = np.dot(a, copy_a)        # doing dot product between copy_a and a matrix

In [ ]:
element_wise_product                             # printing element wise product copy_a and a matrix

array([[640., 490., 360., 250.,   1.],
       [160., 490., 640., 810.,   1.],
       [  4., 160.,   1., 250., 490.],
       [160., 250., 360., 640., 490.],
       [160.,   1., 490., 640., 360.]])

In [ ]:
matrix_multiplication                          # printing matrix multiplication of copy_a and a matrix

array([[1172., 1541., 1416., 1810.,  845.],
       [1016., 1541., 1418., 2030., 1261.],
       [ 802.,  717., 1231., 1470.,  846.],
       [1132., 1277., 1616., 2150., 1409.],
       [ 934., 1036., 1227., 1760., 1415.]])

In [ ]:
# Exercise 10
a /= 18                                # dividing each element of matrix a by 10
copy_a /= 18                           # dividing each element of matrix copy_a by 10

In [ ]:
a                                      # printing matrix a

array([[0.44444444, 0.38888889, 0.33333333, 0.27777778, 0.05555556],
       [0.22222222, 0.38888889, 0.44444444, 0.5       , 0.05555556],
       [0.11111111, 0.22222222, 0.05555556, 0.27777778, 0.38888889],
       [0.22222222, 0.27777778, 0.33333333, 0.44444444, 0.38888889],
       [0.22222222, 0.05555556, 0.38888889, 0.44444444, 0.33333333]])

In [ ]:
copy_a                  #printing matrix copy_a

array([[4.44444444, 3.88888889, 3.33333333, 2.77777778, 0.05555556],
       [2.22222222, 3.88888889, 4.44444444, 5.        , 0.05555556],
       [0.11111111, 2.22222222, 0.05555556, 2.77777778, 3.88888889],
       [2.22222222, 2.77777778, 3.33333333, 4.44444444, 3.88888889],
       [2.22222222, 0.05555556, 3.88888889, 4.44444444, 3.33333333]])

In [ ]:

# Exercise 11
inverse_a = np.linalg.inv(a)                            # calculating the inverse of matrix a
rank_a = np.linalg.matrix_rank(a)                       # calculating the rank of matrix a
condition_number_a = np.linalg.cond(a)                   # calculating the conditional number of matrix a
singular_values_a = np.linalg.svd(a)                     # calculating the singular value of matrix a
norm_a = np.linalg.norm(a)                              # calculating the norm of matrix a

inverse_copy_a = np.linalg.inv(copy_a)                      # calculating the inverse of matrix copy_a
rank_copy_a = np.linalg.matrix_rank(copy_a)                 # calculating the rank of matrix copy_a
condition_number_copy_a = np.linalg.cond(copy_a)            # calculating the conditional number of matrix copy_a
singular_values_copy_a = np.linalg.svd(copy_a)              # calculating the singular values of matrix copy_a
norm_copy_a = np.linalg.norm(copy_a)                        # calculating the norm of matrix copy_a


In [ ]:
inverse_a                             #printing the inverse of matrix a

array([[  3.56603774,  -0.80274443,   4.02915952,  -7.90394511,
          4.06003431],
       [ -0.16981132,   0.07718696,  -1.94511149,   6.29845626,
         -5.06346484],
       [ -1.18867925,  -2.73241852, -10.34305317,  14.63464837,
         -4.35334477],
       [ -0.33962264,   5.06346484,   9.20068611, -15.2212693 ,
          6.23670669],
       [ -0.50943396,  -3.04116638,  -2.5626072 ,   7.44082333,
         -2.09948542]])

In [ ]:
rank_a                          #printing the rank of matrix a

5

In [ ]:

condition_number_a                #printing the conditional number of matrix a

46.01628716644986

In [ ]:
singular_values_a                     #printing the singular value of matrix a

(array([[-0.44342728,  0.58313832, -0.41657344,  0.5351037 , -0.0587584 ],
        [-0.51200502,  0.4138724 ,  0.28222187, -0.67501826, -0.17680966],
        [-0.30253409, -0.51451193, -0.61014191, -0.21700945, -0.47369224],
        [-0.50042979, -0.31079235, -0.09065894, -0.05864327,  0.80082462],
        [-0.44639249, -0.35685421,  0.60524804,  0.45550219, -0.31556519]]),
 array([1.50117416, 0.4621153 , 0.27592003, 0.19764319, 0.03262267]),
 array([[-0.36962902, -0.40141556, -0.48800556, -0.5888883 , -0.34249244],
        [ 0.31509525,  0.36188796,  0.23233303, -0.15306292, -0.83207283],
        [-0.27496443, -0.65016328,  0.57202061,  0.30667759, -0.28359048],
        [ 0.7685492 , -0.47368018,  0.12090315, -0.36817801,  0.18651161],
        [-0.31275558,  0.24661195,  0.60501801, -0.63259475,  0.27412331]]))

In [ ]:
norm_a                          #printing the norm of matrix a

1.607275126832159

In [ ]:
inverse_copy_a              #printing the inverse of copy_a matrix

array([[ 0.43693461, -0.18304531,  0.30202738, -0.604029  ,  0.34810373],
       [-0.05336609,  0.03790299, -0.13585434,  0.49879527, -0.42317337],
       [-0.35631573, -0.03254429, -0.84498452,  1.2292277 , -0.44180272],
       [ 0.16509247,  0.28322684,  0.72451964, -1.21864285,  0.56900508],
       [-0.09482191, -0.21826895, -0.17929827,  0.58513088, -0.1682532 ]])

In [ ]:
rank_copy_a                        #printing the rank of matrix copy_a

5

In [ ]:
condition_number_copy_a                 #printing the conditional number of matrix copy_a

36.74338393677985

In [ ]:
singular_values_copy_a

(array([[-0.44633045,  0.56288875,  0.2185477 ,  0.62946594,  0.19988726],
        [-0.52105009,  0.39394647,  0.02506759, -0.75332107,  0.07205529],
        [-0.26344511, -0.56382338,  0.63323878, -0.04778803,  0.45762956],
        [-0.5118676 , -0.30212016,  0.09730715,  0.12385853, -0.78860976],
        [-0.44484172, -0.34465786, -0.73562795,  0.13658464,  0.35145833]]),
 array([14.59178351,  5.33084596,  3.13395632,  2.13809083,  0.39712683]),
 array([[-0.36300377, -0.39707531, -0.49715291, -0.60505905, -0.31193268],
        [ 0.35214539,  0.30196233,  0.23419213, -0.17022305, -0.83725178],
        [-0.10245897,  0.82452314, -0.53010771, -0.11026631,  0.12841692],
        [ 0.79371389, -0.11047938, -0.1442897 , -0.46457716,  0.34808204],
        [ 0.32209053, -0.24311694, -0.62941189,  0.613952  , -0.2530918 ]]))

In [ ]:
norm_copy_a                 #printing the norm of matrix copy_a

15.99652740093577

In [ ]:
# Exercise 12
column_vector_norm = np.linalg.norm(column_vector)                           # calculating the norm of column vector
inner_product = np.inner(column_vector, column_vector)                       # doing inner product of column vectors
outer_product = np.outer(column_vector, column_vector)                       # doing outer product of column vectors

In [ ]:
column_vector_norm                 # printing the column vector norm


17.146428199482248

In [ ]:
inner_product                  # printing the inner product

294.0

In [ ]:
outer_product                 # printing the outer product

array([[ 49.,  56.,  63.,  70.],
       [ 56.,  64.,  72.,  80.],
       [ 63.,  72.,  81.,  90.],
       [ 70.,  80.,  90., 100.]])

In [ ]:
# Exercise 13
def derivative(f, a, method='central', h=0.01):                    # defining the function derivative
    if method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    elif method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h

def func1(x):                                                   # defining the function func1
    return np.exp(x)

def func2(x):                                                    # defining the function func2
    return np.cos(x)

x_value = 0.5
derivative_func1 = derivative(func1, x_value)                   # calling the function derivative passing func1 and x_value as argument
derivative_func2 = derivative(func2, x_value)                   # calling the function derivative passing func2 and x_value as argument

In [ ]:
derivative_func1                                                # getting the result from derivative function

1.648748749525375

In [ ]:
derivative_func2                                                  # getting the result from derivative function

-0.4794175482185081

In [ ]:
# Exercise 14
# Path to the uploaded file in Google Drive
import io
from google.colab import files, drive                                # importing the file and drive from google colab
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/AWS.xlsx'                      # providing the file path

# Load the Excel file into a pandas DataFrame
data = pd.read_excel(file_path)                                   # reading the file with pandas library

# Display the first few rows of the DataFrame
data.head()                                                        # printing the head or first five rows of dataframe


Mounted at /content/drive


created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15