In [ ]:
# importing neccesary libraries
import numpy as np                    # importing numpy libary
import pandas as pd                   # importing pandas libary




In [ ]:
# Exercise 1
# Create row and column vectors using input method
row_vector = np.array(input("Enter space-separated values for row vector: ").split(), dtype=float)          # entering row vectors
column_vector = np.array(input("Enter space-separated values for column vector: ").split(), dtype=float)    # entering column vectors

Enter space-separated values for row vector: 4 2 6
Enter space-separated values for column vector: 5 4 2


In [ ]:
row_vector                                     # printing row vector using input method

array([4., 2., 6.])

In [ ]:

column_vector                                  # printing column vector using input method

array([5., 4., 2.])

In [ ]:
# Manually create row and column vectors
row_vector_manual = np.array([4, 7, 3])
column_vector_manual = np.array([[2], [6], [3]])

In [ ]:
row_vector_manual                              # printing row vector using manual method

array([4, 7, 3])

In [ ]:
column_vector_manual                           # printing column vector using manual method

array([[2],
       [6],
       [3]])

In [ ]:

# Exercise 2
# Create a 5x5 matrix using input method
a = np.zeros((5, 5))                                                               # initalize the row and column of matrix
for i in range(5):                                                                 # iterates the number of rows form first to fifth
    a[i] = np.array(input(f"Enter values for row {i+1}: ").split(), dtype=float)   # splits the numbers by spacing


Enter values for row 1: 6 8 9 10 7
Enter values for row 2: 4 6 2 4 10
Enter values for row 3: 7 9 8 7 8
Enter values for row 4: 6 2 1 4 2
Enter values for row 5: 9 7 8 7 2


In [ ]:
a                                                                                  # printing the matrix a

array([[ 6.,  8.,  9., 10.,  7.],
       [ 4.,  6.,  2.,  4., 10.],
       [ 7.,  9.,  8.,  7.,  8.],
       [ 6.,  2.,  1.,  4.,  2.],
       [ 9.,  7.,  8.,  7.,  2.]])

In [ ]:
# Manually create a 5x5 matrix                                                    # inserting the elements of matrix manually
b = np.array([[16, 12, 18, 11, 5],
                     [16, 17, 12, 9, 10],
                     [18, 17, 16, 7, 5],
                     [19, 17, 16, 9, 10],
                     [16, 16, 8, 7, 9]])

In [ ]:
b                                                                                # printing the matrix b

array([[16, 12, 18, 11,  5],
       [16, 17, 12,  9, 10],
       [18, 17, 16,  7,  5],
       [19, 17, 16,  9, 10],
       [16, 16,  8,  7,  9]])

In [ ]:
# Exercise 3
third_row =a[2]                                                                  # printing the third row of matrix a and 2 indicates third row
third_row


array([7., 9., 8., 7., 8.])

In [ ]:
# Exercise 4
fourth_column = a[:, 3]                                                          # printing the fourth column of matrix a 3 indicates the fourth column

In [ ]:
fourth_column

array([10.,  4.,  7.,  4.,  7.])

In [ ]:
# Exercise 5
sorted_matrix_row_wise = np.sort(a, axis=1)                                      # sorting matrix a row wise
sorted_matrix_column_wise = np.sort(a, axis=0)                                   # sorting matrix a column wise

In [ ]:
sorted_matrix_row_wise                                                           # printing sorted matrix a row wise

array([[ 6.,  7.,  8.,  9., 10.],
       [ 2.,  4.,  4.,  6., 10.],
       [ 7.,  7.,  8.,  8.,  9.],
       [ 1.,  2.,  2.,  4.,  6.],
       [ 2.,  7.,  7.,  8.,  9.]])

In [ ]:
sorted_matrix_column_wise                                                        # printing sorted matrix a column wise

array([[ 4.,  2.,  1.,  4.,  2.],
       [ 6.,  6.,  2.,  4.,  2.],
       [ 6.,  7.,  8.,  7.,  7.],
       [ 7.,  8.,  8.,  7.,  8.],
       [ 9.,  9.,  9., 10., 10.]])

In [ ]:
# Exercise 6
import numpy as np
b = np.copy(a)                                                         # creating matrix b
b [b > 2] *= 10                                                        # multiplying elements of a matrix by 10 which are greater than 2

In [ ]:
b                                                                      # printing matrix b

array([[ 60.,  80.,  90., 100.,  70.],
       [ 40.,  60.,   2.,  40., 100.],
       [ 70.,  90.,  80.,  70.,  80.],
       [ 60.,   2.,   1.,  40.,   2.],
       [ 90.,  70.,  80.,  70.,   2.]])

In [ ]:
# Exercise 7
matrix_sum = a + b                                                      # summing the matrix a and b
matrix_sum

array([[ 66.,  88.,  99., 110.,  77.],
       [ 44.,  66.,   4.,  44., 110.],
       [ 77.,  99.,  88.,  77.,  88.],
       [ 66.,   4.,   2.,  44.,   4.],
       [ 99.,  77.,  88.,  77.,   4.]])

In [ ]:
# Exercise 8
matrix_difference = a-b                                       # calculating the difference of matrix a and matrix b

In [ ]:
matrix_difference                                             # printing the difference of matrix a and matrix b

array([[-54., -72., -81., -90., -63.],
       [-36., -54.,   0., -36., -90.],
       [-63., -81., -72., -63., -72.],
       [-54.,   0.,   0., -36.,   0.],
       [-81., -63., -72., -63.,   0.]])

In [ ]:
# Exercise 9
element_wise_product = a * b                             # calculating element wise multiplication of matrix a and matrix b
matrix_multiplication = np.dot(a, b)                     # calculating product between matrix a and matrix b

In [ ]:
element_wise_product                                     # printing element wise product of matrix a and matrix b

array([[ 360.,  640.,  810., 1000.,  490.],
       [ 160.,  360.,    4.,  160., 1000.],
       [ 490.,  810.,  640.,  490.,  640.],
       [ 360.,    4.,    1.,  160.,    4.],
       [ 810.,  490.,  640.,  490.,    4.]])

In [ ]:
matrix_multiplication                                     # printing matrix multiplication of matrix a and matrix b

array([[2540., 2280., 1846., 2440., 1974.],
       [1760., 1568., 1336., 1640., 1068.],
       [2480., 2394., 1935., 2460., 2060.],
       [ 930.,  838.,  788., 1050.,  712.],
       [1980., 2014., 1631., 2160., 1988.]])

In [ ]:
# Exercise 10
a /= 18                                                     # dividing each element of matrix a by 18
b /= 18                                                     # dividing each element of matrix b by 18

In [ ]:
a                                                                       # printing matrix a divided by 18

array([[0.33333333, 0.44444444, 0.5       , 0.55555556, 0.38888889],
       [0.22222222, 0.33333333, 0.11111111, 0.22222222, 0.55555556],
       [0.38888889, 0.5       , 0.44444444, 0.38888889, 0.44444444],
       [0.33333333, 0.11111111, 0.05555556, 0.22222222, 0.11111111],
       [0.5       , 0.38888889, 0.44444444, 0.38888889, 0.11111111]])

In [ ]:
b                                                                       # printing matrix b divided by 18

array([[3.33333333, 4.44444444, 5.        , 5.55555556, 3.88888889],
       [2.22222222, 3.33333333, 0.11111111, 2.22222222, 5.55555556],
       [3.88888889, 5.        , 4.44444444, 3.88888889, 4.44444444],
       [3.33333333, 0.11111111, 0.05555556, 2.22222222, 0.11111111],
       [5.        , 3.88888889, 4.44444444, 3.88888889, 0.11111111]])

In [ ]:

# Exercise 11
inverse_a = np.linalg.inv(a)                                        # calculating the inverse of matrix a
rank_a = np.linalg.matrix_rank(a)                                   # calculating the rank of matrix a
condition_number_a = np.linalg.cond(a)                              # calculating the conditional number of matrix a
singular_values_a = np.linalg.svd(a)                                # calculating the singular value of matrix a
norm_a = np.linalg.norm(a)                                          # calculating the norm of matrix a

inverse_b = np.linalg.inv(b)                                        # calculating the inverse of matrix b
rank_b = np.linalg.matrix_rank(b)                                   # calculating the rank of matrix b
condition_number_b = np.linalg.cond(b)                              # calculating the conditional number of matrix b
singular_values_b = np.linalg.svd(b)                                # calculating the singular values of matrix b
norm_b = np.linalg.norm(b)                                          # calculating the norm of matrix b


In [ ]:
inverse_a                                                          # printing the inverse of matrix a

array([[ -4.92631579, -12.97894737,  20.74736842,  12.69473684,
        -13.54736842],
       [  7.01052632,  44.43157895, -65.17894737, -36.75789474,
         50.77894737],
       [ -6.06315789, -32.58947368,  49.07368421,  22.54736842,
        -34.67368421],
       [  7.38947368,  14.96842105, -26.62105263, -10.04210526,
         15.82105263],
       [ -3.97894737, -19.13684211,  31.64210526,  16.48421053,
        -24.44210526]])

In [ ]:
rank_a                                                             # printing the rank of matrix a

5

In [ ]:
condition_number_a                                                # printing the conditional number of matrix a

250.91163636462974

In [ ]:
singular_values_a                                                 # printing the singular value of matrix a

(array([[-0.56068318,  0.05674431,  0.48092731, -0.66585873,  0.08806543],
        [-0.35873902, -0.76767152, -0.29058408,  0.08448686,  0.43635951],
        [-0.54467093, -0.12945976,  0.15371441,  0.47076541, -0.66432338],
        [-0.20986542,  0.15481605, -0.793112  , -0.42860293, -0.34534241],
        [-0.4650062 ,  0.60558458, -0.17780622,  0.37970194,  0.49116996]]),
 array([1.77839259, 0.44795394, 0.25388434, 0.14028697, 0.00708772]),
 array([[-0.43909815, -0.47529538, -0.43893911, -0.46699442, -0.41295978],
        [ 0.34015389, -0.09530846,  0.36451792,  0.17969294, -0.84264391],
        [-0.77894166,  0.14365163,  0.60424085,  0.06692596, -0.05502741],
        [ 0.19161233,  0.48220514,  0.21835442, -0.82441338, -0.05853922],
        [-0.21914095,  0.71543903, -0.51154031,  0.25591044, -0.33609612]]))

In [ ]:
norm_a                                                           # printing the norm of matrix a

1.8567527741187115

In [ ]:
inverse_b                                                       # printing the inverse of matrix b

array([[-0.33712305, -0.1732919 ,  0.5059537 ,  0.35251834, -0.12676445],
       [ 0.05606756,  0.59102114, -0.79063892, -0.60825545,  0.72039058],
       [-0.11420532, -0.53924921,  0.77970143,  0.18666186, -0.41507249],
       [ 0.51077724,  0.25366691, -0.76705259, -0.0653489 ,  0.18690338],
       [-0.10081811, -0.1959777 ,  0.56322888,  0.24635225, -0.44798847]])

In [ ]:
rank_b                                                          # printing the rank of matrix b

5

In [ ]:
condition_number_b                                              # printing the conditional number of matrix b

36.90923981389751

In [ ]:
singular_values_b                                               # printing the singular value of matrix b

(array([[-0.57824574,  0.00907842,  0.32804774, -0.71872181,  0.20340376],
        [-0.34035346, -0.73128421, -0.38946552,  0.19931284,  0.39745934],
        [-0.56026104, -0.142468  ,  0.19973745,  0.33763618, -0.71548389],
        [-0.15497138,  0.24678097, -0.83261713, -0.34344699, -0.32229785],
        [-0.46030731,  0.61963135, -0.08691923,  0.46017316,  0.42995335]]),
 array([17.24559674,  5.43293018,  3.13386869,  1.60992397,  0.46724335]),
 array([[-0.44537326, -0.48204194, -0.43335784, -0.48024289, -0.38838896],
        [ 0.32614134, -0.12378365,  0.38626934,  0.15266109, -0.84011906],
        [-0.70367221,  0.2322773 ,  0.65482084, -0.14503297, -0.03267681],
        [ 0.32066739,  0.56502008, -0.02778037, -0.7519642 , -0.10817959],
        [-0.31191718,  0.61572132, -0.48315101,  0.39947045, -0.36136324]]))

In [ ]:
norm_b                                                                       # printing the norm of matrix b

18.427117028317497

In [ ]:
# Exercise 12
column_vector_norm = np.linalg.norm(column_vector)                           # calculating the norm of column vector
inner_product = np.inner(column_vector, column_vector)                       # doing inner product of column vectors
outer_product = np.outer(column_vector, column_vector)                       # doing outer product of column vectors

In [ ]:
column_vector_norm                                                           # printing the column vector norm


6.708203932499369

In [ ]:
inner_product                                                                # printing the inner product

45.0

In [ ]:
outer_product                                                                # printing the outer product

array([[25., 20., 10.],
       [20., 16.,  8.],
       [10.,  8.,  4.]])

In [ ]:
# Exercise 13
def derivative(f, a, method='central', h=0.01):                 # defining the function derivative
    if method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    elif method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h

def func1(x):                                                   # defining the function func1
    return np.exp(x)

def func2(x):                                                   # defining the function func2
    return np.cos(x)

x_value = 0.5
derivative_func1 = derivative(func1, x_value)                   # calling the function derivative passing func1 and x_value as argument
derivative_func2 = derivative(func2, x_value)                   # calling the function derivative passing func2 and x_value as argument

In [ ]:
derivative_func1                                                # getting the result from derivative func1

1.648748749525375

In [ ]:
derivative_func2                                                # getting the result from derivative func2

-0.4794175482185081

In [ ]:
# Exercise 14
# Path to the uploaded file in Google Drive
import io
from google.colab import files, drive                              # importing the file and drive from google colab
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/AWS.xlsx'                     # providing the file path

# Load the Excel file into a pandas DataFrame
data = pd.read_excel(file_path)                                    # reading the file with pandas library

# Display the first few rows of the DataFrame
data.head()                                                        # printing the head or first five rows of dataframe


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15