In [2]:
a=int(45)
print(a)

45


In [3]:
a=[[1,2,5],[4,2,6],[6,7,8]]
print(a)


[[1, 2, 5], [4, 2, 6], [6, 7, 8]]


In [12]:
#3x3 matrix
import numpy as np

a=[[1,2,5],[4,2,6],[6,7,8]]
print(a)

[[1, 2, 5], [4, 2, 6], [6, 7, 8]]


In [13]:
m = np.array(a)
print(m)

[[1 2 5]
 [4 2 6]
 [6 7 8]]


In [14]:
b=m[0:2,0:2]
print(b)

[[1 2]
 [4 2]]


In [17]:
#3x3 matrix
import numpy as np
a=[[1,2,5],[4,2,6],[6,7,6]]

In [18]:
print(a)

[[1, 2, 5], [4, 2, 6], [6, 7, 6]]


In [19]:
m=np.array(a)

In [20]:
print(m)

[[1 2 5]
 [4 2 6]
 [6 7 6]]


In [22]:
b=m[0:2,0:2]
print(b)

[[1 2]
 [4 2]]
